project:
  type: website
  output-dir: .

website:
  title: "PHY 117"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://phy117.github.io/Spring2024/
        text: "Spring 2024" 
        target: _blank #makes it open in new page

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
self-contained: true


